#include "8bp/Foundation.h"
#include "8bp/Types.h"
#include "8bp/CCNode.h"
#include "8bp/CCDirector.h"
#include "8bp/StateManager.h"
#include "8bp/GameManager.h"
#include "8bp/MainManager.h"
#include "8bp/MenuManager.h"
#include "8bp/VisualCue.h"
#include "8bp/Ball.h"
#include "8bp/UserInfo.h"
#include "8bp/Table.h"

#include "8bp/inc/8bp.h"
#include "8bp/inc/GameConstants.h"
#include "8bp/inc/NumberUtils.h"
#include "8bp/inc/Prediction.fast.h"
// #include "8bp/inc/AutoAim.h"
#include "8bp/inc/AutoPlay.h"
#include "8bp/inc/AutoQueue.h"
#include "8bp/inc/ScreenTable.h"
